language:
  - python

python:
  - 3.6

install:
  - pip install pytest-cov
#  - pip install python-coveralls
  - pip install coveralls

script:
  - py.test -vv exercises.py --cov exercises
  - coveralls

notifications:
  email: false
